/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTD1 (number 24), SW3/SW2/SW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINBUTTON0_SW2_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINBUTTON0_SW2_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON0_SW2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON0_SW2_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON0_SW2_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinButton0(void);

/*! @name PORTC6 (number 44), SW2/SW3/SW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINBUTTON1_SW3_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINBUTTON1_SW3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINBUTTON1_SW3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINBUTTON1_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINBUTTON1_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinButton1(void);

/*! @name PORTB0 (number 46), LED1/LPSPI1_PCS0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINLED1_LED1_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINLED1_LED1_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINLED1_LED1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINLED1_LED1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINLED1_LED1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLED1(void);

/*! @name PORTA21 (number 18), EPaperBusy
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINLED2_LED_R_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINLED2_LED_R_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINLED2_LED_R_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINLED2_LED_R_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINLED2_LED_R_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLED2(void);

/*! @name PORTA19 (number 14), LED_G
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINLED3_LED_G_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINLED3_LED_G_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINLED3_LED_G_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINLED3_LED_G_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINLED3_LED_G_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLED3(void);

/*! @name PORTA20 (number 17), LED_B
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINLED4_LED_B_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINLED4_LED_B_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINLED4_LED_B_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINLED4_LED_B_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINLED4_LED_B_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLED4(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLPUART0_RX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLPUART0_TX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLPUART1_RX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinLPUART1_TX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLPUART0_RX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLPUART0_TX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLPUART1_RX(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLPUART1_TX(void);

/*! @name PORTC6 (number 44), SW2/SW3/SW3
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITPINBUTTON1_SW3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITPINBUTTON1_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_UNINITPINBUTTON1_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinButton1(void);

/*! @name PORTD1 (number 24), SW3/SW2/SW2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITPINBUTTON0_SW2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITPINBUTTON0_SW2_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_UNINITPINBUTTON0_SW2_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinButton0(void);

/*! @name PORTB0 (number 46), LED1/LPSPI1_PCS0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITPINLED1_LED1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITPINLED1_LED1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_UNINITPINLED1_LED1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLED1(void);

/*! @name PORTA21 (number 18), EPaperBusy
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITPINLED2_LED_R_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITPINLED2_LED_R_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_UNINITPINLED2_LED_R_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLED2(void);

/*! @name PORTA19 (number 14), LED_G
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITPINLED3_LED_G_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITPINLED3_LED_G_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_UNINITPINLED3_LED_G_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLED3(void);

/*! @name PORTA20 (number 17), LED_B
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITPINLED4_LED_B_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITPINLED4_LED_B_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_UNINITPINLED4_LED_B_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UnInitPinLED4(void);

#define PCR_DSE_dse1 0x01u /*!<@brief Drive Strength Enable: High */
#define PCR_ODE_ode0 0x00u /*!<@brief Open Drain Enable: Disables */
#define PCR_PE_pe0 0x00u   /*!<@brief Pull Enable: Disables */
#define PCR_PE_pe1 0x01u   /*!<@brief Pull Enable: Enables */
#define PCR_PS_ps1 0x01u   /*!<@brief Pull Select: Enables internal pullup resistor */
#define PCR_SRE_sre0 0x00u /*!<@brief Slew Rate Enable: Fast */

/*! @name PORTB2 (number 48), SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITEPAPERPINS_SCKSI_IO1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEPAPERPINS_SCKSI_IO1_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITEPAPERPINS_SCKSI_IO1_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORTB1 (number 47), SI_IO1/SI-IO1/SI-IO1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITEPAPERPINS_SI_IO1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEPAPERPINS_SI_IO1_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITEPAPERPINS_SI_IO1_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTB3 (number 1), SO_IO1/SO-IO1/SO-IO1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITEPAPERPINS_SO_IO1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEPAPERPINS_SO_IO1_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITEPAPERPINS_SO_IO1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTB4 (number 2), CS
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITEPAPERPINS_EPAPER_CS_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEPAPERPINS_EPAPER_CS_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITEPAPERPINS_EPAPER_CS_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORTA18 (number 13), DC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITEPAPERPINS_EPAPER_DC_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITEPAPERPINS_EPAPER_DC_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITEPAPERPINS_EPAPER_DC_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEPAPERPINS_EPAPER_DC_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITEPAPERPINS_EPAPER_DC_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTB5 (number 3), EPaperReset
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITEPAPERPINS_EPAPER_RST_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITEPAPERPINS_EPAPER_RST_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITEPAPERPINS_EPAPER_RST_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEPAPERPINS_EPAPER_RST_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITEPAPERPINS_EPAPER_RST_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTA21 (number 18), EPaperBusy
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITEPAPERPINS_EPAPER_BUSY_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITEPAPERPINS_EPAPER_BUSY_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITEPAPERPINS_EPAPER_BUSY_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEPAPERPINS_EPAPER_BUSY_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITEPAPERPINS_EPAPER_BUSY_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORTB0 (number 46), LED1/LPSPI1_PCS0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITEPAPERPINS_SPIRAM_CS_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEPAPERPINS_SPIRAM_CS_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITEPAPERPINS_SPIRAM_CS_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitEPaperPins(void);

/*! @name PORTB2 (number 48), SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITEPAPERPINS_SCKSI_IO1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITEPAPERPINS_SCKSI_IO1_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_UNINITEPAPERPINS_SCKSI_IO1_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORTB1 (number 47), SI_IO1/SI-IO1/SI-IO1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITEPAPERPINS_SI_IO1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITEPAPERPINS_SI_IO1_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_UNINITEPAPERPINS_SI_IO1_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB3 (number 1), SO_IO1/SO-IO1/SO-IO1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_UNINITEPAPERPINS_SO_IO1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_UNINITEPAPERPINS_SO_IO1_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_UNINITEPAPERPINS_SO_IO1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief This is a de-initialization function for 'BOARD_InitEPaperPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void BOARD_UnInitEPaperPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
